@url = http://localhost:8080


### First Auth
# @name auth
POST {{url}}/rp/v6.0/auth HTTP/1.1
Content-Type: application/json


### Then Collect until status = complete
POST {{url}}/rp/v6.0/collect HTTP/1.1
Content-Type: application/json

{
  "orderRef":"{{auth.response.body.orderRef}}"
}


### Metrics
GET {{url}}/q/metrics
Accept: text/plain


### Health
GET {{url}}/q/health HTTP/1.1

