name: publish
on: [push]
jobs:
	publish-sim-bankid-image:
		runs-on: ubuntu-latest
			steps:
			- uses: actions/checkout@v2
			- name: Login to GitHub Container Registry
				 uses: docker/login-action@v1
				 with:
					registry: ghcr.io
					username: ${{ github.actor }}
					password: ${{ secrets.GITHUB_TOKEN }}
			- name: Set up JDK 21
				uses: actions/setup-java@v2
				with:
					java-version: '21'
					distribution: 'adopt'
			 - name: Build sim-bankid Docker image
				 run: |
							docker build . --tag swedish-council-for-higher-education/sim-bankid:latest
							docker push ghcr.io/swedish-council-for-higher-education/sim-bankid:latest
